-- begin BOOKING_RESOURCE
alter table BOOKING_RESOURCE add constraint FK_BOOKING_RESOURCE_CATEGORY foreign key (CATEGORY_ID) references BOOKING_CATEGORY(ID)^
create index IDX_BOOKING_RESOURCE_CATEGORY on BOOKING_RESOURCE (CATEGORY_ID)^
-- end BOOKING_RESOURCE
-- begin BOOKING_BOOKING
alter table BOOKING_BOOKING add constraint FK_BOOKING_BOOKING_RESOURCE foreign key (RESOURCE_ID) references BOOKING_RESOURCE(ID)^
alter table BOOKING_BOOKING add constraint FK_BOOKING_BOOKING_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
create index IDX_BOOKING_BOOKING_RESOURCE on BOOKING_BOOKING (RESOURCE_ID)^
create index IDX_BOOKING_BOOKING_OWNER on BOOKING_BOOKING (OWNER_ID)^
-- end BOOKING_BOOKING
